In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [3]:
data = {
    "Transaction_ID":[1,2,3,4,5,6,7,8],
    "Product1":["Milk","Milk","Bread","Milk","Tea","Milk","Bread","Tea"],
    "Product2":["Bread","Butter","Butter","Bread","Sugar","Eggs","Jam","Milk"],
    "Product3":["Butter",None,None,"Eggs",None,None,None,"Sugar"]
}
data=pd.DataFrame(data)
data

   Transaction_ID Product1 Product2 Product3
0               1     Milk    Bread   Butter
1               2     Milk   Butter     None
2               3    Bread   Butter     None
3               4     Milk    Bread     Eggs
4               5      Tea    Sugar     None
5               6     Milk     Eggs     None
6               7    Bread      Jam     None
7               8      Tea     Milk    Sugar

In [4]:
transactions=data.iloc[:,1:].values.tolist()
transactions

[['Milk', 'Bread', 'Butter'],
 ['Milk', 'Butter', None],
 ['Bread', 'Butter', None],
 ['Milk', 'Bread', 'Eggs'],
 ['Tea', 'Sugar', None],
 ['Milk', 'Eggs', None],
 ['Bread', 'Jam', None],
 ['Tea', 'Milk', 'Sugar']]

In [7]:
new_transactions = []
for row in transactions:
    temp = []
    for item in row:
        if pd.notnull(item):
            temp.append(item)
    new_transactions.append(temp)

transactions = new_transactions
transactions

[['Milk', 'Bread', 'Butter'],
 ['Milk', 'Butter'],
 ['Bread', 'Butter'],
 ['Milk', 'Bread', 'Eggs'],
 ['Tea', 'Sugar'],
 ['Milk', 'Eggs'],
 ['Bread', 'Jam'],
 ['Tea', 'Milk', 'Sugar']]

In [9]:

te = TransactionEncoder()
transactions = te.fit(transactions).transform(transactions)

transactions = pd.DataFrame(transactions, columns=te.columns_)

transactions

   Bread  Butter   Eggs    Jam   Milk  Sugar    Tea
0   True    True  False  False   True  False  False
1  False    True  False  False   True  False  False
2   True    True  False  False  False  False  False
3   True   False   True  False   True  False  False
4  False   False  False  False  False   True   True
5  False   False   True  False   True  False  False
6   True   False  False   True  False  False  False
7  False   False  False  False   True   True   True

In [10]:
frequent_items=apriori(transactions, min_support=0.2)
print(frequent_items)

    support itemsets
0     0.500      (0)
1     0.375      (1)
2     0.250      (2)
3     0.625      (4)
4     0.250      (5)
5     0.250      (6)
6     0.250   (0, 1)
7     0.250   (0, 4)
8     0.250   (1, 4)
9     0.250   (2, 4)
10    0.250   (5, 6)

In [12]:
rules=association_rules(frequent_items)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(2),(4),0.25,0.625,0.25,1.0,1.6,1.0,0.09375,inf,0.5,0.4,1.0,0.7
1,(5),(6),0.25,0.250,0.25,1.0,4.0,1.0,0.18750,inf,1.0,1.0,1.0,1.0
2,(6),(5),0.25,0.250,0.25,1.0,4.0,1.0,0.18750,inf,1.0,1.0,1.0,1.0