In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
data={
    'Gender':['F','F','M','F','M','M'],
    'Profile':['HR','Developer', 'Developer','Developer','HR','HR'],
    'Job Role':['Hiring','APP','WEB','APP','Hiring','Hiring']}
df=pd.DataFrame(data)
df

  Gender    Profile Job Role
0      F         HR   Hiring
1      F  Developer      APP
2      M  Developer      WEB
3      F  Developer      APP
4      M         HR   Hiring
5      M         HR   Hiring

In [7]:
df = pd.read_csv("Loan_Approval_Prediction.csv")

In [8]:
df.head()

,Customer ID,Income Level,Credit Score,Employment,Existing Loan,Property,Loan Approved
0,1,High,Excellent,Permanent,No,Own,Yes
1,2,Low,Poor,Temporary,Yes,Rent,No
2,3,Medium,Good,Permanent,No,Own,Yes
3,4,Medium,Fair,Self-Employed,Yes,Rent,No
4,5,High,Good,Permanent,No,Own,Yes

In [10]:
num_data={
    'Age':[22,35,45,30,25],
     'Salary':[20000,50000,80000,40000,25000],
    'Purchased':[0,1,1,0,0]}

In [11]:
num_data=pd.DataFrame(num_data)
num_data

   Age  Salary  Purchased
0   22   20000          0
1   35   50000          1
2   45   80000          1
3   30   40000          0
4   25   25000          0

In [13]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

In [14]:
df=df.drop("Customer ID",axis=1)
df

,Income Level,Credit Score,Employment,Existing Loan,Property,Loan Approved
0,High,Excellent,Permanent,No,Own,Yes
1,Low,Poor,Temporary,Yes,Rent,No
2,Medium,Good,Permanent,No,Own,Yes
3,Medium,Fair,Self-Employed,Yes,Rent,No
4,High,Good,Permanent,No,Own,Yes
5,Low,Fair,Temporary,Yes,Rent,No
6,High,Excellent,Self-Employed,No,Own,Yes
7,Medium,Good,Permanent,Yes,Own,Yes
8,Low,Poor,Temporary,Yes,Rent,No
9,Medium,Excellent,Permanent,No,Own,Yes
10,High,Fair,Self-Employed,No,Own,Yes
11,Low,Good,Permanent,Yes,Rent,Yes
12,Medium,Fair,Permanent,No,Rent,Yes
13,High,Good,Self-Employed,Yes,Own,Yes
14,Low,Poor,Temporary,No,Rent,No
15,Medium,Excellent,Permanent,No,Own,Yes
16,High,Excellent,Permanent,Yes,Own,Yes
17,Low,Fair,Self-Employed,Yes,Rent,No
18,Medium,Good,Temporary,No,Rent,Yes
19,High,Excellent,Self-Employed,Yes,Own,Yes

In [16]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df_encoded = df.copy()

for column in df.columns:
    df_encoded[column] = encoder.fit_transform(df[column])

df_encoded.head()

,Income Level,Credit Score,Employment,Existing Loan,Property,Loan Approved
0,0,0,0,0,0,1
1,1,3,2,1,1,0
2,2,2,0,0,0,1
3,2,1,1,1,1,0
4,0,2,0,0,0,1

In [17]:
X=df_encoded.drop("Loan Approved", axis=1)
y=df_encoded["Loan Approved"]

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [19]:
model=DecisionTreeClassifier(criterion="entropy",random_state=42)

In [20]:
model.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [21]:
y_pred =model.predict(X_test)
print(y_pred)

[1 0 1 0]

In [22]:
comparision =pd.DataFrame({"Actual":y_test,"Predicted":y_pred})
comparision

    Actual  Predicted
0        1          1
17       0          0
15       1          1
1        0          0

In [25]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
df_encoded.head(1)

Accuracy: 1.0

,Income Level,Credit Score,Employment,Existing Loan,Property,Loan Approved
0,0,0,0,0,0,1

In [26]:
new_customer=pd.DataFrame({
    "Income Level":[1],
    "Credit Score":[3],
    "Employment":[0],
    "Existing Loan":[0],
    "Property":[1]
})
prediction=model.predict(new_customer)
print(prediction)

[1]